version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'CartoDB/app-dev-builder-team'
    groups:
      prod:
        patterns:
          - '@mapbox/*'
          - '@math.gl/*'
          - '@types/mapbox*'
      dev:
        dependency-type: 'development'
    ignore:
      # Update would require workaround for antimeridian:
      # https://github.com/mapbox/tile-cover/issues/87
      - dependency-name: '@mapbox/tile-cover'
